name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --no-daemon

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: jeongdaehyun/be-spring:latest
